### ISSUE TITLE
Visual Glitch with Xycraft

### ISSUE THREAD

**Issue by ltombely** [lucaargolo/mekanism-covers#11]
# Visual Glitch with Xycraft mod

## What Happens

The colors get distorted when placing the crafted covers from the Xycraft mod and its addons. After placing a cover on a cable, every block of that type, including those placed after the glitch, becomes visually glitched.

**Comment by lucaargolo** [comment]
![image](https://github.com/user-attachments/assets/b4e29688-ac36-4e95-988d-aa25fe3e917c)
Should be fixed on 1.2-BETA!
