### ISSUE TITLE
[Ad Astra Integration] Make covered cables and pipes act as full blocks for ad astra's oxygen sealer

### ISSUE THREAD

**Issue by Kevadroz** [lucaargolo/mekanism-covers#2]
Basically just that, currently the oxygen sealer ignores a cable with a cover when considering if a room is sealed / air-tight, it would be nice if it considered it a full block / wall.
![Captura de pantalla_20241014_172310](https://github.com/user-attachments/assets/d16d8d62-8751-44b2-9af4-2bfd429e1c15)

**Comment by lucaargolo** [comment]
I'll take a look into this when I have time. I'm not familiar with Ad Astra systems.

**Comment by Kevadroz** [comment]
> I'll take a look into this when I have time. I'm not familiar with Ad Astra systems.

I have already inspected how it works, Ad Astra performs some checks in order to determine if the block is "a valid wall", [the relevant code is here](https://github.com/terrarium-earth/Ad-Astra/blob/bfa70ac3db6dca1c02ed6fad5be62649b2c23906/common/src/main/java/earth/terrarium/adastra/common/utils/floodfill/FloodFill3D.java#L25).
So I would say that the easiest way to make this work would be making `BlockState#isCollisionShapeFullBlock` return true for covered blocks, which a covered cable should already do anyways.

I may look into this myself later.

**Comment by Kevadroz** [comment]
You may wanna make the mekanism cables have a boolean block state property indicating if the state has a cover or not, block states have caches and these caches ignore block entities.

Or figure out a way to either bypass or integrate that cache. What do other mods do with this cache?
Yeah, if you haven't already dealt with this, you may wanna look into the cache system.

It may be affecting the light system.

**Comment by Kevadroz** [comment]
After some research looks like you should add this to `BlockTransmitterMixin`
```
@Override
public boolean hasDynamicShape() {
    return true;
}
```

**Comment by lucaargolo** [comment]
[mekanismcovers-1.1-BETA+1.20.jar.zip](https://github.com/user-attachments/files/17456891/mekanismcovers-1.1-BETA%2B1.20.jar.zip)
Hey, sorry for the delay. I added the override you talked about, let me know if it works!

**Comment by lucaargolo** [comment]
Oops, closed it by mistake

**Comment by Kevadroz** [comment]
It works. Also probably fixes some bugs with the cache, but I haven't looked if those even existed before.

**Comment by lucaargolo** [comment]
Thanks! It should be available on all platforms shortly.
