### ISSUE TITLE
Visual glitch for items

### ISSUE THREAD

**Issue by nirahiel** [lucaargolo/mekanism-covers#3]
Just having the mod installed makes item glitch hard in their pipes.  I have Embeddium (Rubidium fork). And Oculus
I haven't even placed a single cover yet.

**Comment by lucaargolo** [comment]
A screenshot would be nice? Also have you tried disabling the advanced rendering in the settings? Are you running latest embeddium and oculus? Please give more context.

**Comment by nirahiel** [comment]
I can't show a screenshot, as it's not that sort of glitch. Instead of flowing smoothly inside the pipes, the items get all jittery. A screenshot wouldn't capture that as it's a motion issue. My versions for embeddium and oculus are as follows : 
Embeddium 0.3.31+mc1.20.1
Oculus 1.7.0
Haven't tried disabling the advanced rendering.

**Comment by Kevadroz** [comment]
> I can't show a screenshot, as it's not that sort of glitch. Instead of flowing smoothly inside the pipes, the items get all jittery. A screenshot wouldn't capture that as it's a motion issue. My versions for embeddium and oculus are as follows : Embeddium 0.3.31+mc1.20.1 Oculus 1.7.0 Haven't tried disabling the advanced rendering.

Can you try capturing a gif?

**Comment by nirahiel** [comment]
Not really able to capture a gif, no. Plus I kinda got rid of mekanism entirely now. The unsightly pipes and wires though the holes in the walls (seriously that's the only reason I wanted covers, just to go through walls. I like visual pipes otherwise), plus the armor rendering issue with shaders, and the fact I wanted mekanism only for the x5 ores (which I found out I have another mod that also has a x5 ore mult machine, and its better cause it multiplies raw metal instead of metal ore (in stone))

So yeah, this can be closed (or marked as standby or something idk), I won't be waiting for this anymore.
