### ISSUE TITLE
Suggestion: Connected Textures

### ISSUE THREAD

**Issue by mxnmnm** [lucaargolo/mekanism-covers#4]
Can you make it so that blocks that normally would have connected textures would also have them when used as a cover?

**Comment by lucaargolo** [comment]
Oof, thats definitely something I want to do, but its a bit hard and time consuming since every other mod has its own connected texture implementation... For know I think its out of the scope for this mod :/

**Comment by mxnmnm** [comment]
I think supporting one or two implementations would be good enough such as athena and fusion. Mainly the ones that are most widely used.

**Comment by lucaargolo** [comment]
I'll take a look how hard it is to integrate it with Athena and Fusion, but no promises. If any other dev wants to help feel free to chime in.

**Comment by mxnmnm** [comment]
I found these wikis for implementation. Any ideas of how difficult either one would be? 
https://wiki.terrarium.earth/athena
https://github.com/SuperMartijn642/Fusion/wiki

**Comment by Leclowndu93150** [comment]
difficult

**Comment by lucaargolo** [comment]
Should be fixed in 1.2-BETA
