### ISSUE TITLE
using this mod will cause rendering problems

### ISSUE THREAD

**Issue by Nobodycare233** [lucaargolo/mekanism-covers#5]
![2024-10-20_21 26 30](https://github.com/user-attachments/assets/5b76a582-b299-4316-bc20-26527a544912)

**Comment by lucaargolo** [comment]
Have you tried disabling the advanced cover rendering in the config file?

**Comment by Nobodycare233** [comment]
> Have you tried disabling the advanced cover rendering in the config file?

let me try

**Comment by TwTlinmiao** [comment]
![image](https://github.com/user-attachments/assets/228cb5d4-0413-450e-b1a3-6adcf1a45556)
Even if it is disabled, the problem still occurs

**Comment by lucaargolo** [comment]
Weird, are you sure it is a problem with this mod? Can you send your complete mod list? It shouldn't change any blocks that aren't cables.

**Comment by TwTlinmiao** [comment]
I'll send out the full list of mods a little later

**Comment by Nobodycare233** [comment]
I tried, but it didn't work,even...saw for myself
![2024-10-22_16 15 45](https://github.com/user-attachments/assets/9f5808fd-1eb6-437d-9f1f-e99cf8a684ee)

**Comment by TwTlinmiao** [comment]
List of mods
![image](https://github.com/user-attachments/assets/3853bcb5-fb8c-44a6-9e7b-b7f45d35dd32)

**Comment by jpeaglesandkatz** [comment]
I've heard reports that the cover rendering causes iris shader compilation errors.. Which basically means that you can't use shaders at all.. I'm experiencing this issue. Someone suggested disabling enhanced cover rendering in the config but spitting through them, I can't find a config for it.

**Comment by lucaargolo** [comment]
There should be a file called mekanismcovers.json in your .minecraft/config folder. Disabling that stops the mod from ever touching at iris or sodium, so it should fix that issue.

**Comment by jpeaglesandkatz** [comment]
> There should be a file called mekanismcovers.json in your .minecraft/config folder. Disabling that stops the mod from ever touching at iris or sodium, so it should fix that issue.

Yeah I was just about to delete this post as I found that setting.. Still hope it will be fixed at some point though.. Disabling this options at least allowed me to enable a few shaders.... 

Thanks for the quick reply!
