### ISSUE TITLE
Visual glitching with Logitstical Transporters

### ISSUE THREAD

**Issue by liquidthex** [lucaargolo/mekanism-covers#7]
Hello, thanks for a great mod!

I am running ATM10 version 1.16 which has incorporated your mod into their pack.

Since the modpack added your mod the logistical transporter pipes are visually glitchy.
I have opened a ticket on the ATM10 issue tracker: https://github.com/AllTheMods/ATM-10/issues/1072
And I see this is likely a duplicate of a closed ticket here: #3 Visual glitch for items 

I have tried disabling advanced rendering in the json config, but unfortunately that did not help.
ATM10 does include Iris, if that helps, however I have shaders disabled.

Here are some video to assist:
Expected behavior (ATM modpack 1.15, without Mekanism Covers): https://imgur.com/7lffRHU

Current behavior (ATM modpack 1.16, with Mekanism Covers): https://imgur.com/f0di4xo

Thank you for your efforts, let me know if I can do anything else to help.

**Comment by lucaargolo** [comment]
Oh, seems to be something related to the server -> client syncing... I probably broke something when I implemented the syncing for the cover state. I'll take a look asap, thanks for reporting.

**Comment by lucaargolo** [comment]
This should be fixed in 1.2-BETA
