### ISSUE TITLE
Remove Iris integration

### ISSUE THREAD

**Issue by IMS212** [lucaargolo/mekanism-covers#8]
The bugs being fixed by Iris integration are a platform issue that I plan to fix on my side. The injection strategy being used is too brittle for any mod to pull off, and is causing issues in various modpacks.

I plan to introduce a way for vertex alpha to work in shader packs very soon natively.

**Comment by lucaargolo** [comment]
I figured this would cause issues, but I never imagine so many modpacks including the mod out of nowhere...

I'll change the config so the Iris integration is off by default. But I'll keep this issue open until the vertex alpha thing is implemented by Iris and I can properly implement a fix. 

Would be great to have an issue in the Iris repo as well so I could keep track of when it gets added.

**Comment by IMS212** [comment]
Since it’s a platform issue, it’ll be incremental; shader packs need to update to support this new tech. But the injection being used here is incorrect on many deferred packs, as output 0 is not guaranteed to be color.

**Comment by lucaargolo** [comment]
Should be fixed in 1.2-BETA.
