### ISSUE TITLE
Glass Covers render connected blocks as transpearant

### ISSUE THREAD

**Issue by eodrambo** [lucaargolo/mekanism-covers#9]
expected behavior - glass cover is transparent, showing pipe below, and surrounding blocks

what's happening - glass covers render connected blocks as transparent until air, almost looks like you can peer through the world

![2024-11-14_23 09 46](https://github.com/user-attachments/assets/29c9a66f-8a18-468c-b4cd-69c2b2e8f88f)
![2024-11-14_23 10 00](https://github.com/user-attachments/assets/9d4d7439-c148-4cb9-b6ca-c0833c53e9dc)

**Comment by lucaargolo** [comment]
Should be fixed in 1.2-BETA
